version: '3.8'

services:
  payhere-db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: payhere
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql/data:/var/lib/mysql